//! Printer geometry Amber can slice for.
//!
//! Build area and pixel grid come from manufacturer figures collected in the
//! UVtools printer profiles (`PrusaSlicer/printer` in
//! <https://github.com/sn4k3/UVtools>). Amber does not include that program.
//! Lift speeds in those notes are millimetres per minute and are stored here
//! as millimetres per second. A Photon Workshop v516 file is written only when
//! the profile says `FILEVERSION_516`. Every machine can also be saved as `.sl1`.

#[derive(Clone, Copy, Debug)]
pub struct PrinterProfile {
    pub id: &'static str,
    pub name: &'static str,
    pub vendor: &'static str,
    pub res_x: u32,
    pub res_y: u32,
    pub size_x: f32,
    pub size_y: f32,
    pub size_z: f32,
    pub pixel_x_um: f32,
    pub pixel_y_um: f32,
    /// Community profile mirror. The Photon M3 Max keeps its own orientation.
    pub mirror_x: bool,
    pub mirror_y: bool,
    /// Suffix the printer itself reads.
    pub printer_extension: &'static str,
    pub file_version: u32,
    pub native_photon: bool,
    pub format_name: &'static str,
    pub light_off_s: f32,
    pub lift_mm: f32,
    pub lift_speed: f32,
    pub retract_speed: f32,
}

pub const PRINTERS: &[PrinterProfile] = &[
    PrinterProfile {
        id: "anet-n4",
        name: "Anet N4",
        vendor: "Anet",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 135.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "n4",
        file_version: 0,
        native_photon: false,
        format_name: "N4",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 1.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anet-n7",
        name: "Anet N7",
        vendor: "Anet",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 300.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "n7",
        file_version: 0,
        native_photon: false,
        format_name: "N7",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 1.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-d2",
        name: "Anycubic Photon D2",
        vendor: "Anycubic",
        res_x: 2560,
        res_y: 1440,
        size_x: 130.56,
        size_y: 73.44,
        size_z: 165.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "dl2p",
        file_version: 517,
        native_photon: false,
        format_name: "DL2P",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-m3-max",
        name: "Anycubic Photon M3 Max",
        vendor: "Anycubic",
        res_x: 6480,
        res_y: 3600,
        size_x: 298.08,
        size_y: 165.6,
        size_z: 300.0,
        pixel_x_um: 46.0,
        pixel_y_um: 46.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm3m",
        file_version: 516,
        native_photon: true,
        format_name: "PM3M",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-m3-plus",
        name: "Anycubic Photon M3 Plus",
        vendor: "Anycubic",
        res_x: 5760,
        res_y: 3600,
        size_x: 198.15,
        size_y: 123.84,
        size_z: 245.0,
        pixel_x_um: 34.401,
        pixel_y_um: 34.4,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwmb",
        file_version: 517,
        native_photon: false,
        format_name: "PWMB",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-m3-premium",
        name: "Anycubic Photon M3 Premium",
        vendor: "Anycubic",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 250.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm3r",
        file_version: 517,
        native_photon: false,
        format_name: "PM3R",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-m3",
        name: "Anycubic Photon M3",
        vendor: "Anycubic",
        res_x: 4096,
        res_y: 2560,
        size_x: 163.84,
        size_y: 102.4,
        size_z: 180.0,
        pixel_x_um: 40.0,
        pixel_y_um: 40.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm3",
        file_version: 516,
        native_photon: true,
        format_name: "PM3",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-2",
        name: "Anycubic Photon Mono 2",
        vendor: "Anycubic",
        res_x: 4096,
        res_y: 2560,
        size_x: 143.36,
        size_y: 89.6,
        size_z: 165.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm3n",
        file_version: 517,
        native_photon: false,
        format_name: "PM3N",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-4-ultra",
        name: "Anycubic Photon Mono 4 Ultra",
        vendor: "Anycubic",
        res_x: 9024,
        res_y: 5120,
        size_x: 153.408,
        size_y: 87.04,
        size_z: 165.0,
        pixel_x_um: 17.0,
        pixel_y_um: 17.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm4u",
        file_version: 0,
        native_photon: false,
        format_name: "PM4U",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-4",
        name: "Anycubic Photon Mono 4",
        vendor: "Anycubic",
        res_x: 9024,
        res_y: 5120,
        size_x: 153.408,
        size_y: 87.04,
        size_z: 165.0,
        pixel_x_um: 17.0,
        pixel_y_um: 17.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm4n",
        file_version: 0,
        native_photon: false,
        format_name: "PM4N",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-4k",
        name: "Anycubic Photon Mono 4K",
        vendor: "Anycubic",
        res_x: 3840,
        res_y: 2400,
        size_x: 134.4,
        size_y: 84.0,
        size_z: 165.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwma",
        file_version: 516,
        native_photon: true,
        format_name: "PWMA",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m5",
        name: "Anycubic Photon Mono M5",
        vendor: "Anycubic",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 200.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm5",
        file_version: 517,
        native_photon: false,
        format_name: "PM5",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m5s-pro",
        name: "Anycubic Photon Mono M5s Pro",
        vendor: "Anycubic",
        res_x: 13312,
        res_y: 5120,
        size_x: 223.642,
        size_y: 126.976,
        size_z: 200.0,
        pixel_x_um: 16.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "m5sp",
        file_version: 518,
        native_photon: false,
        format_name: "M5SP",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m5s",
        name: "Anycubic Photon Mono M5s",
        vendor: "Anycubic",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 200.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm5s",
        file_version: 518,
        native_photon: false,
        format_name: "PM5S",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m7-max",
        name: "Anycubic Photon Mono M7 Max",
        vendor: "Anycubic",
        res_x: 6480,
        res_y: 3600,
        size_x: 298.08,
        size_y: 165.6,
        size_z: 300.0,
        pixel_x_um: 46.0,
        pixel_y_um: 46.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm7m",
        file_version: 0,
        native_photon: false,
        format_name: "PM7M",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m7-pro",
        name: "Anycubic Photon Mono M7 Pro",
        vendor: "Anycubic",
        res_x: 13312,
        res_y: 5120,
        size_x: 223.642,
        size_y: 126.976,
        size_z: 230.0,
        pixel_x_um: 16.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwsz",
        file_version: 0,
        native_photon: false,
        format_name: "PWSZ",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-m7",
        name: "Anycubic Photon Mono M7",
        vendor: "Anycubic",
        res_x: 13312,
        res_y: 5120,
        size_x: 223.642,
        size_y: 126.976,
        size_z: 230.0,
        pixel_x_um: 16.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pm7",
        file_version: 0,
        native_photon: false,
        format_name: "PM7",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-se",
        name: "Anycubic Photon Mono SE",
        vendor: "Anycubic",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 160.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwms",
        file_version: 516,
        native_photon: true,
        format_name: "PWMS",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-sq",
        name: "Anycubic Photon Mono SQ",
        vendor: "Anycubic",
        res_x: 2400,
        res_y: 2560,
        size_x: 120.0,
        size_y: 128.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pmsq",
        file_version: 516,
        native_photon: true,
        format_name: "PMSQ",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-x-6k",
        name: "Anycubic Photon Mono X 6K",
        vendor: "Anycubic",
        res_x: 5760,
        res_y: 3600,
        size_x: 198.15,
        size_y: 123.84,
        size_z: 245.0,
        pixel_x_um: 34.401,
        pixel_y_um: 34.4,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwmb",
        file_version: 516,
        native_photon: true,
        format_name: "PWMB",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-x-6ks",
        name: "Anycubic Photon Mono X 6Ks",
        vendor: "Anycubic",
        res_x: 5760,
        res_y: 3600,
        size_x: 195.84,
        size_y: 122.4,
        size_z: 200.0,
        pixel_x_um: 34.0,
        pixel_y_um: 34.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "px6s",
        file_version: 517,
        native_photon: false,
        format_name: "PX6S",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-x",
        name: "Anycubic Photon Mono X",
        vendor: "Anycubic",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 245.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwmx",
        file_version: 516,
        native_photon: true,
        format_name: "PWMX",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono-x2",
        name: "Anycubic Photon Mono X2",
        vendor: "Anycubic",
        res_x: 4096,
        res_y: 2560,
        size_x: 196.61,
        size_y: 122.88,
        size_z: 200.0,
        pixel_x_um: 48.0005,
        pixel_y_um: 48.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pmx2",
        file_version: 517,
        native_photon: false,
        format_name: "PMX2",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-mono",
        name: "Anycubic Photon Mono",
        vendor: "Anycubic",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 165.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwmo",
        file_version: 516,
        native_photon: true,
        format_name: "PWMO",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-p1-max",
        name: "Anycubic Photon P1 Max",
        vendor: "Anycubic",
        res_x: 11520,
        res_y: 8640,
        size_x: 285.696,
        size_y: 214.272,
        size_z: 300.0,
        pixel_x_um: 24.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pp1m",
        file_version: 0,
        native_photon: false,
        format_name: "PP1M",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-p1",
        name: "Anycubic Photon P1",
        vendor: "Anycubic",
        res_x: 13312,
        res_y: 5120,
        size_x: 223.642,
        size_y: 126.976,
        size_z: 230.0,
        pixel_x_um: 16.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pp1",
        file_version: 0,
        native_photon: false,
        format_name: "PP1",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "anycubic-photon-s",
        name: "Anycubic Photon S",
        vendor: "Anycubic",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 165.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pws",
        file_version: 1,
        native_photon: false,
        format_name: "PWS",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-ultra",
        name: "Anycubic Photon Ultra",
        vendor: "Anycubic",
        res_x: 1280,
        res_y: 720,
        size_x: 102.4,
        size_y: 57.6,
        size_z: 165.0,
        pixel_x_um: 80.0,
        pixel_y_um: 80.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "dlp",
        file_version: 516,
        native_photon: true,
        format_name: "DLP",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-x",
        name: "Anycubic Photon X",
        vendor: "Anycubic",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 245.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pwx",
        file_version: 1,
        native_photon: false,
        format_name: "PWX",
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon-zero",
        name: "Anycubic Photon Zero",
        vendor: "Anycubic",
        res_x: 480,
        res_y: 854,
        size_x: 55.4,
        size_y: 98.63,
        size_z: 150.0,
        pixel_x_um: 115.4167,
        pixel_y_um: 115.4918,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "pw0",
        file_version: 1,
        native_photon: false,
        format_name: "PW0",
        light_off_s: 2.5,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "anycubic-photon",
        name: "Anycubic Photon",
        vendor: "Anycubic",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 155.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "photon",
        file_version: 2,
        native_photon: false,
        format_name: "PHOTON",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "concepts3d-athena-12k",
        name: "Concepts3D Athena 12K",
        vendor: "Concepts3D",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 245.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "nanodlp",
        file_version: 0,
        native_photon: false,
        format_name: "NANODLP",
        light_off_s: 1.0,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "concepts3d-athena-8k",
        name: "Concepts3D Athena 8K",
        vendor: "Concepts3D",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 245.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "nanodlp",
        file_version: 0,
        native_photon: false,
        format_name: "NANODLP",
        light_off_s: 1.0,
        lift_mm: 8.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "creality-ct-005-pro",
        name: "Creality CT-005 Pro",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 250.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-ct-133-pro",
        name: "Creality CT-133 Pro",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2160,
        size_x: 293.76,
        size_y: 165.24,
        size_z: 300.0,
        pixel_x_um: 76.5,
        pixel_y_um: 76.5,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-lite-cl-89l",
        name: "Creality Halot Lite CL-89L",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-mage-cl-103l",
        name: "Creality Halot Mage CL-103L",
        vendor: "Creality",
        res_x: 7680,
        res_y: 4320,
        size_x: 228.096,
        size_y: 128.304,
        size_z: 230.0,
        pixel_x_um: 29.7,
        pixel_y_um: 29.7,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "cxdlpv4",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLPV4",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-mage-pro-cl-103",
        name: "Creality Halot Mage Pro CL-103",
        vendor: "Creality",
        res_x: 7680,
        res_y: 4320,
        size_x: 228.096,
        size_y: 128.304,
        size_z: 230.0,
        pixel_x_um: 29.7,
        pixel_y_um: 29.7,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "cxdlpv4",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLPV4",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-max-cl-133",
        name: "Creality Halot Max CL-133",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2160,
        size_x: 293.76,
        size_y: 165.24,
        size_z: 300.0,
        pixel_x_um: 76.5,
        pixel_y_um: 76.5,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-one-cl-60",
        name: "Creality Halot One CL-60",
        vendor: "Creality",
        res_x: 1620,
        res_y: 2560,
        size_x: 81.0,
        size_y: 128.0,
        size_z: 160.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-one-plus-cl-79",
        name: "Creality Halot One Plus CL-79",
        vendor: "Creality",
        res_x: 4320,
        res_y: 2560,
        size_x: 172.8,
        size_y: 102.4,
        size_z: 160.0,
        pixel_x_um: 40.0,
        pixel_y_um: 40.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-one-pro-cl-70",
        name: "Creality Halot One Pro CL-70",
        vendor: "Creality",
        res_x: 2560,
        res_y: 2400,
        size_x: 130.56,
        size_y: 122.4,
        size_z: 160.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-ray-cl925",
        name: "Creality Halot Ray CL925",
        vendor: "Creality",
        res_x: 5760,
        res_y: 3600,
        size_x: 198.14,
        size_y: 123.84,
        size_z: 210.0,
        pixel_x_um: 34.3993,
        pixel_y_um: 34.4,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-sky-cl-89",
        name: "Creality Halot Sky CL-89",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-halot-sky-plus-cl-92",
        name: "Creality Halot Sky Plus CL-92",
        vendor: "Creality",
        res_x: 5760,
        res_y: 3600,
        size_x: 198.14,
        size_y: 123.84,
        size_z: 210.0,
        pixel_x_um: 34.3993,
        pixel_y_um: 34.4,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "cxdlp",
        file_version: 0,
        native_photon: false,
        format_name: "CXDLP",
        light_off_s: 2.0,
        lift_mm: 6.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-ld-002h",
        name: "Creality LD-002H",
        vendor: "Creality",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 160.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 0.833333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-ld-002r",
        name: "Creality LD-002R",
        vendor: "Creality",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 160.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "creality-ld-006",
        name: "Creality LD-006",
        vendor: "Creality",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 245.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 1.333333,
    },
    PrinterProfile {
        id: "epax-dx1-pro",
        name: "EPAX DX1 PRO",
        vendor: "EPAX",
        res_x: 4098,
        res_y: 2560,
        size_x: 143.43,
        size_y: 89.6,
        size_z: 155.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-dx10-pro-5k",
        name: "EPAX DX10 Pro 5K",
        vendor: "EPAX",
        res_x: 4920,
        res_y: 2880,
        size_x: 221.4,
        size_y: 129.6,
        size_z: 120.0,
        pixel_x_um: 45.0,
        pixel_y_um: 45.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 7.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-dx10-pro-8k",
        name: "EPAX DX10 Pro 8K",
        vendor: "EPAX",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 120.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 7.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-e10-5k",
        name: "EPAX E10 5K",
        vendor: "EPAX",
        res_x: 4920,
        res_y: 2880,
        size_x: 221.4,
        size_y: 129.6,
        size_z: 250.0,
        pixel_x_um: 45.0,
        pixel_y_um: 45.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-e10-8k",
        name: "EPAX E10 8K",
        vendor: "EPAX",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 250.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 7.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-e10-mono",
        name: "EPAX E10 Mono",
        vendor: "EPAX",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 250.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-e6-mono",
        name: "EPAX E6 Mono",
        vendor: "EPAX",
        res_x: 1620,
        res_y: 2560,
        size_x: 81.0,
        size_y: 128.0,
        size_z: 155.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x1-4ks",
        name: "EPAX X1 4KS",
        vendor: "EPAX",
        res_x: 4098,
        res_y: 2560,
        size_x: 143.43,
        size_y: 89.6,
        size_z: 155.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x1",
        name: "EPAX X1",
        vendor: "EPAX",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 155.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x10-4k-mono",
        name: "EPAX X10 4K Mono",
        vendor: "EPAX",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 250.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x10-5k",
        name: "EPAX X10 5K",
        vendor: "EPAX",
        res_x: 4920,
        res_y: 2880,
        size_x: 221.4,
        size_y: 129.6,
        size_z: 250.0,
        pixel_x_um: 45.0,
        pixel_y_um: 45.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x10",
        name: "EPAX X10",
        vendor: "EPAX",
        res_x: 1600,
        res_y: 2560,
        size_x: 135.36,
        size_y: 216.57,
        size_z: 250.0,
        pixel_x_um: 84.6,
        pixel_y_um: 84.5977,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x133-4k-mono",
        name: "EPAX X133 4K Mono",
        vendor: "EPAX",
        res_x: 3840,
        res_y: 2160,
        size_x: 293.76,
        size_y: 165.24,
        size_z: 400.0,
        pixel_x_um: 76.5,
        pixel_y_um: 76.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 12.0,
        lift_speed: 0.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x133-6k",
        name: "EPAX X133 6K",
        vendor: "EPAX",
        res_x: 5760,
        res_y: 3240,
        size_x: 288.0,
        size_y: 162.0,
        size_z: 400.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 12.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x156-4k-color",
        name: "EPAX X156 4K Color",
        vendor: "EPAX",
        res_x: 3840,
        res_y: 2160,
        size_x: 345.6,
        size_y: 194.4,
        size_z: 400.0,
        pixel_x_um: 90.0,
        pixel_y_um: 90.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 12.0,
        lift_speed: 0.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "epax-x1k-2k-mono",
        name: "EPAX X1K 2K Mono",
        vendor: "EPAX",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 155.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-jupiter-2",
        name: "Elegoo Jupiter 2",
        vendor: "Elegoo",
        res_x: 15120,
        res_y: 6230,
        size_x: 302.4,
        size_y: 161.98,
        size_z: 300.0,
        pixel_x_um: 20.0,
        pixel_y_um: 26.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 51,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 7.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-jupiter",
        name: "Elegoo Jupiter",
        vendor: "Elegoo",
        res_x: 5448,
        res_y: 3064,
        size_x: 277.848,
        size_y: 156.264,
        size_z: 300.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 7.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-2-pro",
        name: "Elegoo Mars 2 Pro",
        vendor: "Elegoo",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 160.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 4,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-mars-2",
        name: "Elegoo Mars 2",
        vendor: "Elegoo",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 150.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 4,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-mars-3",
        name: "Elegoo Mars 3",
        vendor: "Elegoo",
        res_x: 4098,
        res_y: 2560,
        size_x: 143.43,
        size_y: 89.6,
        size_z: 175.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-4-dlp",
        name: "Elegoo Mars 4 DLP",
        vendor: "Elegoo",
        res_x: 2560,
        res_y: 1440,
        size_x: 132.8,
        size_y: 74.7,
        size_z: 150.0,
        pixel_x_um: 51.875,
        pixel_y_um: 51.875,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-4-max",
        name: "Elegoo Mars 4 Max",
        vendor: "Elegoo",
        res_x: 5760,
        res_y: 3600,
        size_x: 195.84,
        size_y: 122.4,
        size_z: 150.0,
        pixel_x_um: 34.0,
        pixel_y_um: 34.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-4-ultra",
        name: "Elegoo Mars 4 Ultra",
        vendor: "Elegoo",
        res_x: 8520,
        res_y: 4320,
        size_x: 153.36,
        size_y: 77.76,
        size_z: 165.0,
        pixel_x_um: 18.0,
        pixel_y_um: 18.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-4",
        name: "Elegoo Mars 4",
        vendor: "Elegoo",
        res_x: 8520,
        res_y: 4320,
        size_x: 153.36,
        size_y: 77.76,
        size_z: 175.0,
        pixel_x_um: 18.0,
        pixel_y_um: 18.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-5-ultra",
        name: "Elegoo Mars 5 Ultra",
        vendor: "Elegoo",
        res_x: 8520,
        res_y: 4320,
        size_x: 153.36,
        size_y: 77.76,
        size_z: 165.0,
        pixel_x_um: 18.0,
        pixel_y_um: 18.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 0.5,
        retract_speed: 0.5,
    },
    PrinterProfile {
        id: "elegoo-mars-5",
        name: "Elegoo Mars 5",
        vendor: "Elegoo",
        res_x: 4098,
        res_y: 2560,
        size_x: 143.43,
        size_y: 89.6,
        size_z: 150.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars-c",
        name: "Elegoo Mars C",
        vendor: "Elegoo",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 150.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-mars",
        name: "Elegoo Mars",
        vendor: "Elegoo",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 150.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 0,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-2",
        name: "Elegoo Saturn 2",
        vendor: "Elegoo",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 250.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-3-ultra",
        name: "Elegoo Saturn 3 Ultra",
        vendor: "Elegoo",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 260.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-3",
        name: "Elegoo Saturn 3",
        vendor: "Elegoo",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 250.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-4-ultra-12k",
        name: "Elegoo Saturn 4 Ultra 12K",
        vendor: "Elegoo",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 220.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 0.5,
        retract_speed: 0.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-4-ultra-16k",
        name: "Elegoo Saturn 4 Ultra 16K",
        vendor: "Elegoo",
        res_x: 15120,
        res_y: 6230,
        size_x: 211.68,
        size_y: 118.37,
        size_z: 220.0,
        pixel_x_um: 14.0,
        pixel_y_um: 19.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 0.5,
        retract_speed: 0.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-4",
        name: "Elegoo Saturn 4",
        vendor: "Elegoo",
        res_x: 11520,
        res_y: 5120,
        size_x: 218.88,
        size_y: 122.88,
        size_z: 220.0,
        pixel_x_um: 19.0,
        pixel_y_um: 24.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 0.5,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-8k",
        name: "Elegoo Saturn 8K",
        vendor: "Elegoo",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 210.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn-s",
        name: "Elegoo Saturn S",
        vendor: "Elegoo",
        res_x: 4098,
        res_y: 2560,
        size_x: 196.704,
        size_y: 122.88,
        size_z: 210.0,
        pixel_x_um: 48.0,
        pixel_y_um: 48.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "elegoo-saturn",
        name: "Elegoo Saturn",
        vendor: "Elegoo",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.166667,
        retract_speed: 3.5,
    },
    PrinterProfile {
        id: "emake3d-galaxy-1",
        name: "Emake3D Galaxy 1",
        vendor: "Emake3D",
        res_x: 8000,
        res_y: 4000,
        size_x: 400.0,
        size_y: 200.0,
        size_z: 400.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "qdt",
        file_version: 0,
        native_photon: false,
        format_name: "QDT",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-explorer-max",
        name: "FlashForge Explorer MAX",
        vendor: "Flashforge",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-focus-13-3",
        name: "FlashForge Focus 13.3",
        vendor: "Flashforge",
        res_x: 3842,
        res_y: 2171,
        size_x: 292.0,
        size_y: 165.0,
        size_z: 400.0,
        pixel_x_um: 76.0021,
        pixel_y_um: 76.0018,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-focus-8-9",
        name: "FlashForge Focus 8.9",
        vendor: "Flashforge",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-foto-13-3",
        name: "FlashForge Foto 13.3",
        vendor: "Flashforge",
        res_x: 3842,
        res_y: 2171,
        size_x: 292.0,
        size_y: 165.0,
        size_z: 400.0,
        pixel_x_um: 76.0021,
        pixel_y_um: 76.0018,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-foto-6-0",
        name: "FlashForge Foto 6.0",
        vendor: "Flashforge",
        res_x: 2600,
        res_y: 1560,
        size_x: 130.0,
        size_y: 78.0,
        size_z: 155.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-foto-8-9",
        name: "FlashForge Foto 8.9",
        vendor: "Flashforge",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-foto-8-9s",
        name: "FlashForge Foto 8.9S",
        vendor: "Flashforge",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "flashforge-hunter",
        name: "FlashForge Hunter",
        vendor: "Flashforge",
        res_x: 1920,
        res_y: 1080,
        size_x: 120.0,
        size_y: 67.5,
        size_z: 150.0,
        pixel_x_um: 62.5,
        pixel_y_um: 62.5,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "kelant-s400",
        name: "Kelant S400",
        vendor: "Kelant",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 15.0,
        lift_speed: 0.5,
        retract_speed: 5.0,
    },
    PrinterProfile {
        id: "longer-orange-10",
        name: "Longer Orange 10",
        vendor: "Longer",
        res_x: 480,
        res_y: 854,
        size_x: 55.44,
        size_y: 98.64,
        size_z: 140.0,
        pixel_x_um: 115.5,
        pixel_y_um: 115.5035,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "lgs",
        file_version: 0,
        native_photon: false,
        format_name: "LGS",
        light_off_s: 0.0,
        lift_mm: 4.0,
        lift_speed: 2.5,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "longer-orange-120",
        name: "Longer Orange 120",
        vendor: "Longer",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 150.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "lgs120",
        file_version: 0,
        native_photon: false,
        format_name: "LGS120",
        light_off_s: 0.0,
        lift_mm: 4.0,
        lift_speed: 2.5,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "longer-orange-30",
        name: "Longer Orange 30",
        vendor: "Longer",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 170.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "lgs30",
        file_version: 0,
        native_photon: false,
        format_name: "LGS30",
        light_off_s: 0.0,
        lift_mm: 4.0,
        lift_speed: 2.5,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "longer-orange-4k",
        name: "Longer Orange 4K",
        vendor: "Longer",
        res_x: 3840,
        res_y: 6480,
        size_x: 120.96,
        size_y: 68.04,
        size_z: 190.0,
        pixel_x_um: 31.5,
        pixel_y_um: 10.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "lgs4k",
        file_version: 0,
        native_photon: false,
        format_name: "LGS4K",
        light_off_s: 0.0,
        lift_mm: 4.0,
        lift_speed: 2.5,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-bene4-mono",
        name: "Nova3D Bene4 Mono",
        vendor: "Nova3D",
        res_x: 1566,
        res_y: 2549,
        size_x: 79.865,
        size_y: 129.998,
        size_z: 150.0,
        pixel_x_um: 50.9994,
        pixel_y_um: 51.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "rgb",
        file_version: 0,
        native_photon: false,
        format_name: "RGB",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-bene4",
        name: "Nova3D Bene4",
        vendor: "Nova3D",
        res_x: 1352,
        res_y: 2512,
        size_x: 70.0,
        size_y: 130.0,
        size_z: 150.0,
        pixel_x_um: 51.7751,
        pixel_y_um: 51.7516,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "cws",
        file_version: 0,
        native_photon: false,
        format_name: "CWS",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-bene5",
        name: "Nova3D Bene5",
        vendor: "Nova3D",
        res_x: 1566,
        res_y: 2549,
        size_x: 79.865,
        size_y: 129.998,
        size_z: 150.0,
        pixel_x_um: 50.9994,
        pixel_y_um: 51.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "rgb",
        file_version: 0,
        native_photon: false,
        format_name: "RGB",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-bene6",
        name: "Nova3D Bene6",
        vendor: "Nova3D",
        res_x: 4098,
        res_y: 2560,
        size_x: 143.43,
        size_y: 89.6,
        size_z: 180.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "cws",
        file_version: 0,
        native_photon: false,
        format_name: "CWS",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-elfin",
        name: "Nova3D Elfin",
        vendor: "Nova3D",
        res_x: 1410,
        res_y: 2531,
        size_x: 73.0,
        size_y: 131.0,
        size_z: 150.0,
        pixel_x_um: 51.773,
        pixel_y_um: 51.7582,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "cws",
        file_version: 0,
        native_photon: false,
        format_name: "CWS",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-elfin2-mono-se",
        name: "Nova3D Elfin2 Mono SE",
        vendor: "Nova3D",
        res_x: 1470,
        res_y: 2549,
        size_x: 75.0,
        size_y: 130.0,
        size_z: 150.0,
        pixel_x_um: 51.02,
        pixel_y_um: 51.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "rgb",
        file_version: 0,
        native_photon: false,
        format_name: "RGB",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-elfin2",
        name: "Nova3D Elfin2",
        vendor: "Nova3D",
        res_x: 1352,
        res_y: 2512,
        size_x: 70.0,
        size_y: 130.0,
        size_z: 150.0,
        pixel_x_um: 51.7751,
        pixel_y_um: 51.7516,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "cws",
        file_version: 0,
        native_photon: false,
        format_name: "CWS",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-elfin3-mini",
        name: "Nova3D Elfin3 Mini",
        vendor: "Nova3D",
        res_x: 1079,
        res_y: 1904,
        size_x: 68.0,
        size_y: 120.0,
        size_z: 150.0,
        pixel_x_um: 63.0213,
        pixel_y_um: 63.0252,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "cws",
        file_version: 0,
        native_photon: false,
        format_name: "CWS",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-whale",
        name: "Nova3D Whale",
        vendor: "Nova3D",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 250.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "rgb",
        file_version: 0,
        native_photon: false,
        format_name: "RGB",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-whale2",
        name: "Nova3D Whale2",
        vendor: "Nova3D",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 250.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "rgb",
        file_version: 0,
        native_photon: false,
        format_name: "RGB",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "nova3d-whale3-pro",
        name: "Nova3D Whale3 Pro",
        vendor: "Nova3D",
        res_x: 7680,
        res_y: 4320,
        size_x: 228.096,
        size_y: 128.304,
        size_z: 260.0,
        pixel_x_um: 29.7,
        pixel_y_um: 29.7,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "peopoly-phenom-forge",
        name: "Peopoly Phenom Forge",
        vendor: "Peopoly",
        res_x: 5760,
        res_y: 3240,
        size_x: 288.0,
        size_y: 162.0,
        size_z: 350.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "osf",
        file_version: 0,
        native_photon: false,
        format_name: "OSF",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "peopoly-phenom-l",
        name: "Peopoly Phenom L",
        vendor: "Peopoly",
        res_x: 3840,
        res_y: 2160,
        size_x: 345.6,
        size_y: 194.4,
        size_z: 400.0,
        pixel_x_um: 90.0,
        pixel_y_um: 90.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 9.0,
        lift_speed: 0.75,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "peopoly-phenom-noir",
        name: "Peopoly Phenom Noir",
        vendor: "Peopoly",
        res_x: 3840,
        res_y: 2160,
        size_x: 293.76,
        size_y: 165.24,
        size_z: 400.0,
        pixel_x_um: 76.5,
        pixel_y_um: 76.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 8.0,
        lift_speed: 0.75,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "peopoly-phenom-xxl-v2",
        name: "Peopoly Phenom XXL V2",
        vendor: "Peopoly",
        res_x: 3840,
        res_y: 2160,
        size_x: 526.08,
        size_y: 295.92,
        size_z: 550.0,
        pixel_x_um: 137.0,
        pixel_y_um: 137.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "osf",
        file_version: 0,
        native_photon: false,
        format_name: "OSF",
        light_off_s: 0.0,
        lift_mm: 14.0,
        lift_speed: 0.583333,
        retract_speed: 1.666667,
    },
    PrinterProfile {
        id: "peopoly-phenom-xxl",
        name: "Peopoly Phenom XXL",
        vendor: "Peopoly",
        res_x: 3840,
        res_y: 2160,
        size_x: 526.08,
        size_y: 295.92,
        size_z: 550.0,
        pixel_x_um: 137.0,
        pixel_y_um: 137.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 14.0,
        lift_speed: 0.583333,
        retract_speed: 1.666667,
    },
    PrinterProfile {
        id: "peopoly-phenom",
        name: "Peopoly Phenom",
        vendor: "Peopoly",
        res_x: 3840,
        res_y: 2160,
        size_x: 276.48,
        size_y: 155.52,
        size_z: 400.0,
        pixel_x_um: 72.0,
        pixel_y_um: 72.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 12.0,
        lift_speed: 0.8,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-shuffle-16",
        name: "Phrozen Shuffle 16",
        vendor: "Phrozen",
        res_x: 3840,
        res_y: 2160,
        size_x: 337.92,
        size_y: 190.08,
        size_z: 400.0,
        pixel_x_um: 88.0,
        pixel_y_um: 88.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 8.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-shuffle-4k",
        name: "Phrozen Shuffle 4K",
        vendor: "Phrozen",
        res_x: 2160,
        res_y: 3840,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 170.0,
        pixel_x_um: 31.5,
        pixel_y_um: 31.5,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-shuffle-lite",
        name: "Phrozen Shuffle Lite",
        vendor: "Phrozen",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 170.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 3.333333,
    },
    PrinterProfile {
        id: "phrozen-shuffle-xl-lite",
        name: "Phrozen Shuffle XL Lite",
        vendor: "Phrozen",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-shuffle-xl",
        name: "Phrozen Shuffle XL",
        vendor: "Phrozen",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 6.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-shuffle",
        name: "Phrozen Shuffle",
        vendor: "Phrozen",
        res_x: 1440,
        res_y: 2560,
        size_x: 67.68,
        size_y: 120.32,
        size_z: 200.0,
        pixel_x_um: 47.0,
        pixel_y_um: 47.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 3.333333,
    },
    PrinterProfile {
        id: "phrozen-sonic-4k",
        name: "Phrozen Sonic 4K",
        vendor: "Phrozen",
        res_x: 3840,
        res_y: 2160,
        size_x: 134.4,
        size_y: 75.6,
        size_z: 200.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mega-8k",
        name: "Phrozen Sonic Mega 8K",
        vendor: "Phrozen",
        res_x: 7680,
        res_y: 4320,
        size_x: 330.24,
        size_y: 185.76,
        size_z: 400.0,
        pixel_x_um: 43.0,
        pixel_y_um: 43.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mighty-4k",
        name: "Phrozen Sonic Mighty 4K",
        vendor: "Phrozen",
        res_x: 3840,
        res_y: 2400,
        size_x: 199.68,
        size_y: 124.8,
        size_z: 220.0,
        pixel_x_um: 52.0,
        pixel_y_um: 52.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 6.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mighty-8k",
        name: "Phrozen Sonic Mighty 8K",
        vendor: "Phrozen",
        res_x: 7680,
        res_y: 4320,
        size_x: 218.88,
        size_y: 123.12,
        size_z: 235.0,
        pixel_x_um: 28.5,
        pixel_y_um: 28.5,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mighty-revo",
        name: "Phrozen Sonic Mighty Revo",
        vendor: "Phrozen",
        res_x: 13320,
        res_y: 5120,
        size_x: 223.776,
        size_y: 126.976,
        size_z: 235.0,
        pixel_x_um: 16.8,
        pixel_y_um: 24.8,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mini-4k",
        name: "Phrozen Sonic Mini 4K",
        vendor: "Phrozen",
        res_x: 3840,
        res_y: 2160,
        size_x: 134.4,
        size_y: 75.6,
        size_z: 130.0,
        pixel_x_um: 35.0,
        pixel_y_um: 35.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mini-8k-s",
        name: "Phrozen Sonic Mini 8K S",
        vendor: "Phrozen",
        res_x: 7536,
        res_y: 3240,
        size_x: 165.792,
        size_y: 71.28,
        size_z: 170.0,
        pixel_x_um: 22.0,
        pixel_y_um: 22.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "goo",
        file_version: 0,
        native_photon: false,
        format_name: "GOO",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mini-8k",
        name: "Phrozen Sonic Mini 8K",
        vendor: "Phrozen",
        res_x: 7500,
        res_y: 3240,
        size_x: 165.0,
        size_y: 71.28,
        size_z: 180.0,
        pixel_x_um: 22.0,
        pixel_y_um: 22.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "encrypted",
        file_version: 0,
        native_photon: false,
        format_name: "ENCRYPTED",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.333333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "phrozen-sonic-mini",
        name: "Phrozen Sonic Mini",
        vendor: "Phrozen",
        res_x: 1080,
        res_y: 1920,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 130.0,
        pixel_x_um: 63.0,
        pixel_y_um: 63.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "phz",
        file_version: 0,
        native_photon: false,
        format_name: "PHZ",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 2.5,
        retract_speed: 3.333333,
    },
    PrinterProfile {
        id: "phrozen-sonic",
        name: "Phrozen Sonic",
        vendor: "Phrozen",
        res_x: 1080,
        res_y: 1920,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 170.0,
        pixel_x_um: 63.0,
        pixel_y_um: 63.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 3.333333,
    },
    PrinterProfile {
        id: "phrozen-transform",
        name: "Phrozen Transform",
        vendor: "Phrozen",
        res_x: 3840,
        res_y: 2160,
        size_x: 291.84,
        size_y: 164.16,
        size_z: 400.0,
        pixel_x_um: 76.0,
        pixel_y_um: 76.0,
        mirror_x: false,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 8.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "qidi-i-box-mono",
        name: "QIDI I-Box Mono",
        vendor: "QIDI",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.333333,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "qidi-s-box",
        name: "QIDI S-Box",
        vendor: "QIDI",
        res_x: 1600,
        res_y: 2560,
        size_x: 135.36,
        size_y: 216.576,
        size_z: 200.0,
        pixel_x_um: 84.6,
        pixel_y_um: 84.6,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 7.0,
        lift_speed: 1.083333,
        retract_speed: 1.083333,
    },
    PrinterProfile {
        id: "qidi-shadow5-5",
        name: "QIDI Shadow5.5",
        vendor: "QIDI",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 150.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 1.083333,
    },
    PrinterProfile {
        id: "qidi-shadow6-0-pro",
        name: "QIDI Shadow6.0 Pro",
        vendor: "QIDI",
        res_x: 1440,
        res_y: 2560,
        size_x: 74.52,
        size_y: 132.48,
        size_z: 150.0,
        pixel_x_um: 51.75,
        pixel_y_um: 51.75,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "ctb",
        file_version: 3,
        native_photon: false,
        format_name: "CTB",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 1.083333,
    },
    PrinterProfile {
        id: "uvtools-prusa-sl1",
        name: "UVtools Prusa SL1",
        vendor: "Prusa",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 150.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "sl1",
        file_version: 0,
        native_photon: false,
        format_name: "SL1",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "uvtools-prusa-sl1s-speed",
        name: "UVtools Prusa SL1S SPEED",
        vendor: "Prusa",
        res_x: 1620,
        res_y: 2560,
        size_x: 81.0,
        size_y: 128.0,
        size_z: 150.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "sl1",
        file_version: 0,
        native_photon: false,
        format_name: "SL1",
        light_off_s: 1.0,
        lift_mm: 6.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
    },
    PrinterProfile {
        id: "uniformation-gkone",
        name: "UniFormation GKone",
        vendor: "Uniformation",
        res_x: 4920,
        res_y: 2880,
        size_x: 221.4,
        size_y: 129.6,
        size_z: 245.0,
        pixel_x_um: 45.0,
        pixel_y_um: 45.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "jxs",
        file_version: 0,
        native_photon: false,
        format_name: "JXS",
        light_off_s: 1.5,
        lift_mm: 5.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "uniformation-gktwo",
        name: "UniFormation GKtwo",
        vendor: "Uniformation",
        res_x: 7680,
        res_y: 4320,
        size_x: 228.089,
        size_y: 128.3,
        size_z: 245.0,
        pixel_x_um: 29.6991,
        pixel_y_um: 29.6991,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "gktwo",
        file_version: 4,
        native_photon: false,
        format_name: "GKTWO",
        light_off_s: 1.5,
        lift_mm: 5.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "uniz-ibee-klipper",
        name: "Uniz IBEE (Klipper)",
        vendor: "Uniz",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 220.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 2.0,
        lift_mm: 4.0,
        lift_speed: 8.0,
        retract_speed: 8.0,
    },
    PrinterProfile {
        id: "uniz-ibee",
        name: "Uniz IBEE",
        vendor: "Uniz",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 220.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: false,
        mirror_y: true,
        printer_extension: "zcode",
        file_version: 0,
        native_photon: false,
        format_name: "ZCODE",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 2.5,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "voxelab-ceres-8-9",
        name: "Voxelab Ceres 8.9",
        vendor: "Voxelab",
        res_x: 3840,
        res_y: 2400,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 50.0,
        pixel_y_um: 50.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "fdg",
        file_version: 0,
        native_photon: false,
        format_name: "FDG",
        light_off_s: 0.0,
        lift_mm: 8.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "voxelab-polaris-5-5",
        name: "Voxelab Polaris 5.5",
        vendor: "Voxelab",
        res_x: 1440,
        res_y: 2560,
        size_x: 68.04,
        size_y: 120.96,
        size_z: 155.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.25,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "fdg",
        file_version: 0,
        native_photon: false,
        format_name: "FDG",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.083333,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "voxelab-proxima-6-svgx",
        name: "Voxelab Proxima 6 - SVGX",
        vendor: "Voxelab",
        res_x: 2560,
        res_y: 1620,
        size_x: 130.56,
        size_y: 82.62,
        size_z: 155.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "svgx",
        file_version: 0,
        native_photon: false,
        format_name: "SVGX",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "voxelab-proxima-6",
        name: "Voxelab Proxima 6",
        vendor: "Voxelab",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 155.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "fdg",
        file_version: 0,
        native_photon: false,
        format_name: "FDG",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "wanhao-cgr-mini-mono",
        name: "Wanhao CGR Mini Mono",
        vendor: "Wanhao",
        res_x: 1620,
        res_y: 2560,
        size_x: 82.62,
        size_y: 130.56,
        size_z: 200.0,
        pixel_x_um: 51.0,
        pixel_y_um: 51.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 0.833333,
        retract_speed: 1.666667,
    },
    PrinterProfile {
        id: "wanhao-cgr-mono",
        name: "Wanhao CGR Mono",
        vendor: "Wanhao",
        res_x: 1620,
        res_y: 2560,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 200.0,
        pixel_x_um: 118.5185,
        pixel_y_um: 46.875,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 6.0,
        lift_speed: 0.833333,
        retract_speed: 1.0,
    },
    PrinterProfile {
        id: "wanhao-d7",
        name: "Wanhao D7",
        vendor: "Wanhao",
        res_x: 2560,
        res_y: 1440,
        size_x: 120.96,
        size_y: 68.5,
        size_z: 180.0,
        pixel_x_um: 47.25,
        pixel_y_um: 47.5694,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "xml",
        file_version: 0,
        native_photon: false,
        format_name: "XML",
        light_off_s: 2.5,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "wanhao-d8",
        name: "Wanhao D8",
        vendor: "Wanhao",
        res_x: 2560,
        res_y: 1600,
        size_x: 192.0,
        size_y: 120.0,
        size_z: 180.0,
        pixel_x_um: 75.0,
        pixel_y_um: 75.0,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zip",
        file_version: 0,
        native_photon: false,
        format_name: "ZIP",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.0,
        retract_speed: 2.5,
    },
    PrinterProfile {
        id: "zortrax-inkspire",
        name: "Zortrax Inkspire",
        vendor: "Zortrax",
        res_x: 1440,
        res_y: 2560,
        size_x: 74.67,
        size_y: 132.88,
        size_z: 175.0,
        pixel_x_um: 51.8542,
        pixel_y_um: 51.9062,
        mirror_x: true,
        mirror_y: false,
        printer_extension: "zcodex",
        file_version: 0,
        native_photon: false,
        format_name: "ZCODEX",
        light_off_s: 0.0,
        lift_mm: 5.0,
        lift_speed: 1.666667,
        retract_speed: 1.666667,
    },
];

pub fn find(id: &str) -> Option<&'static PrinterProfile> {
    PRINTERS.iter().find(|p| p.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn m3_max_is_the_known_panel_and_ids_are_unique() {
        let mut ids = std::collections::HashSet::new();
        for p in PRINTERS {
            assert!(ids.insert(p.id), "duplicate {}", p.id);
            assert!(p.res_x > 1 && p.res_y > 1);
            assert!(p.size_x > 1.0 && p.size_y > 1.0 && p.size_z > 1.0);
            let wx = p.res_x as f32 * p.pixel_x_um / 1000.0;
            let hy = p.res_y as f32 * p.pixel_y_um / 1000.0;
            assert!(
                (wx - p.size_x).abs() < 0.05,
                "{} x {} vs {}",
                p.name,
                wx,
                p.size_x
            );
            assert!(
                (hy - p.size_y).abs() < 0.05,
                "{} y {} vs {}",
                p.name,
                hy,
                p.size_y
            );
            if p.native_photon {
                assert_eq!(p.file_version, 516, "{}", p.name);
                assert!((p.pixel_x_um - p.pixel_y_um).abs() < 0.05, "{}", p.name);
            }
        }
        let m = find("anycubic-photon-m3-max").unwrap();
        assert_eq!(m.res_x, 6480);
        assert_eq!(m.res_y, 3600);
        assert!((m.pixel_x_um - 46.0).abs() < 0.01);
        assert!((m.size_z - 300.0).abs() < 0.01);
        assert!(m.native_photon);
        assert_eq!(m.printer_extension, "pm3m");
        assert!(PRINTERS.len() > 100);
    }
}
