//! Resin names and the exposure tables Amber can actually cite.
//!
//! A row in `PROFILES` is a manufacturer starting point for one printer and
//! one layer height. Bottles without a row are listed so you can find them,
//! but Amber does not invent a cure time for a printer that table never measured.
//! Run a RERF on the bottle in the vat before a long print.

#[derive(Clone, Copy, Debug)]
pub struct Resin {
    pub id: &'static str,
    pub vendor: &'static str,
    pub name: &'static str,
    pub family: &'static str,
    /// IPA, water, or whichever the bottle allows.
    pub wash: &'static str,
    pub density_g_ml: f32,
}

#[derive(Clone, Copy, Debug)]
pub struct ResinProfile {
    pub resin_id: &'static str,
    pub machine_id: &'static str,
    pub layer_mm: f32,
    pub exposure_s: f32,
    pub bottom_exposure_s: f32,
    pub bottom_layers: u32,
    pub light_off_s: f32,
    pub lift_mm: f32,
    pub lift_speed: f32,
    pub retract_speed: f32,
    pub source: &'static str,
}

pub const RESINS: &[Resin] = &[
    Resin {
        id: "anycubic-colored-uv",
        vendor: "Anycubic",
        name: "Colored UV",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-plant-based",
        vendor: "Anycubic",
        name: "Plant-Based",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-dlp-craftsman",
        vendor: "Anycubic",
        name: "DLP Craftsman",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-uv-tough",
        vendor: "Anycubic",
        name: "UV Tough",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-water-wash",
        vendor: "Anycubic",
        name: "Water-Wash+",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-abs-like",
        vendor: "Anycubic",
        name: "ABS-Like+",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-abs-like-pro",
        vendor: "Anycubic",
        name: "ABS-Like Pro",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-high-clear",
        vendor: "Anycubic",
        name: "High Clear",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-standard-resin",
        vendor: "Anycubic",
        name: "Standard Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-plant-based-uv-resin",
        vendor: "Anycubic",
        name: "Plant-Based UV Resin",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-abs-like-pro-2",
        vendor: "Anycubic",
        name: "ABS-Like Pro 2",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-tough-resin",
        vendor: "Anycubic",
        name: "Tough Resin",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-high-clear-resin",
        vendor: "Anycubic",
        name: "High-Clear Resin",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-craftsman-resin",
        vendor: "Anycubic",
        name: "Craftsman Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "anycubic-castable-jewelry-resin",
        vendor: "Anycubic",
        name: "Castable Jewelry Resin",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-standard-resin",
        vendor: "Elegoo",
        name: "Standard Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-water-washable",
        vendor: "Elegoo",
        name: "Water-Washable",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-abs-like-resin-1-0",
        vendor: "Elegoo",
        name: "ABS-Like Resin 1.0",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-abs-like-resin-2-0",
        vendor: "Elegoo",
        name: "ABS-Like Resin 2.0",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-plant-based-resin",
        vendor: "Elegoo",
        name: "Plant-Based Resin",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-8k-standard-resin",
        vendor: "Elegoo",
        name: "8K Standard Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-8k-space-grey",
        vendor: "Elegoo",
        name: "8K Space Grey",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-thermochromic-color-changing-resin",
        vendor: "Elegoo",
        name: "Thermochromic Color-Changing Resin",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "elegoo-rapid-resin",
        vendor: "Elegoo",
        name: "Rapid Resin",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-aqua-4k",
        vendor: "Phrozen",
        name: "Aqua 4K",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-aqua-8k",
        vendor: "Phrozen",
        name: "Aqua 8K",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-rock-black-stiff",
        vendor: "Phrozen",
        name: "Rock-Black Stiff",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-abs-like-matte-grey",
        vendor: "Phrozen",
        name: "ABS-Like Matte Grey",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-water-washable-model",
        vendor: "Phrozen",
        name: "Water-Washable Model",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-castable-dental-w20",
        vendor: "Phrozen",
        name: "Castable Dental W20",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-castable-jewelry-violet",
        vendor: "Phrozen",
        name: "Castable Jewelry VIOLET",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-protowhite-rigid",
        vendor: "Phrozen",
        name: "Protowhite Rigid",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-speed-resin",
        vendor: "Phrozen",
        name: "Speed Resin",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "phrozen-rpg-resin",
        vendor: "Phrozen",
        name: "RPG Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-fast",
        vendor: "Siraya Tech",
        name: "Fast",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-blu",
        vendor: "Siraya Tech",
        name: "Blu",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-tenacious",
        vendor: "Siraya Tech",
        name: "Tenacious",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-cast-true-blue",
        vendor: "Siraya Tech",
        name: "Cast True Blue",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-sculpt",
        vendor: "Siraya Tech",
        name: "Sculpt",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-build",
        vendor: "Siraya Tech",
        name: "Build",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-defiant-25",
        vendor: "Siraya Tech",
        name: "Defiant 25",
        family: "High-temperature",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "siraya-tech-easy",
        vendor: "Siraya Tech",
        name: "Easy",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-standard-grey",
        vendor: "Formlabs",
        name: "Standard Grey",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-standard-white",
        vendor: "Formlabs",
        name: "Standard White",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-standard-black",
        vendor: "Formlabs",
        name: "Standard Black",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-standard-clear",
        vendor: "Formlabs",
        name: "Standard Clear",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-draft-resin-v2",
        vendor: "Formlabs",
        name: "Draft Resin v2",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-tough-2000",
        vendor: "Formlabs",
        name: "Tough 2000",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-tough-1500",
        vendor: "Formlabs",
        name: "Tough 1500",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-durable-resin",
        vendor: "Formlabs",
        name: "Durable Resin",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-rigid-10k",
        vendor: "Formlabs",
        name: "Rigid 10K",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-rigid-4000",
        vendor: "Formlabs",
        name: "Rigid 4000",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-elastic-50a",
        vendor: "Formlabs",
        name: "Elastic 50A",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-flexible-80a",
        vendor: "Formlabs",
        name: "Flexible 80A",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-silicone-40a",
        vendor: "Formlabs",
        name: "Silicone 40A",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-high-temp-resin",
        vendor: "Formlabs",
        name: "High Temp Resin",
        family: "High-temperature",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-castable-wax-40",
        vendor: "Formlabs",
        name: "Castable Wax 40",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-castable-wax",
        vendor: "Formlabs",
        name: "Castable Wax",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-dental-surgical-guide",
        vendor: "Formlabs",
        name: "Dental Surgical Guide",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-dental-lt-clear-v2",
        vendor: "Formlabs",
        name: "Dental LT Clear v2",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-dental-temporary-cb",
        vendor: "Formlabs",
        name: "Dental Temporary CB",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-dental-permanent-crown",
        vendor: "Formlabs",
        name: "Dental Permanent Crown",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-denture-base",
        vendor: "Formlabs",
        name: "Denture Base",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-denture-teeth",
        vendor: "Formlabs",
        name: "Denture Teeth",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-flame-retardant-resin",
        vendor: "Formlabs",
        name: "Flame Retardant Resin",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-esd-resin",
        vendor: "Formlabs",
        name: "ESD Resin",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-clear",
        vendor: "Formlabs",
        name: "BioMed Clear",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-amber",
        vendor: "Formlabs",
        name: "BioMed Amber",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-white",
        vendor: "Formlabs",
        name: "BioMed White",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-black",
        vendor: "Formlabs",
        name: "BioMed Black",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-elastic-50a",
        vendor: "Formlabs",
        name: "BioMed Elastic 50A",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "formlabs-biomed-flex-80a",
        vendor: "Formlabs",
        name: "BioMed Flex 80A",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-standard-resin",
        vendor: "eSUN",
        name: "Standard Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-bio-based-pla-resin",
        vendor: "eSUN",
        name: "Bio-Based PLA Resin",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-water-washable-resin",
        vendor: "eSUN",
        name: "Water-Washable Resin",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-hard-tough-resin",
        vendor: "eSUN",
        name: "Hard-Tough Resin",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-pmma-like-clear",
        vendor: "eSUN",
        name: "PMMA-Like Clear",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-castable-jewelry-resin",
        vendor: "eSUN",
        name: "Castable Jewelry Resin",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "esun-dental-model-resin",
        vendor: "eSUN",
        name: "Dental Model Resin",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sunlu-standard-photopolymer",
        vendor: "Sunlu",
        name: "Standard Photopolymer",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sunlu-abs-like-resin",
        vendor: "Sunlu",
        name: "ABS-Like Resin",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sunlu-water-washable-resin",
        vendor: "Sunlu",
        name: "Water-Washable Resin",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sunlu-high-toughness-resin",
        vendor: "Sunlu",
        name: "High-Toughness Resin",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sunlu-plant-based-resin",
        vendor: "Sunlu",
        name: "Plant-Based Resin",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "creality-standard-rigid-resin",
        vendor: "Creality",
        name: "Standard Rigid Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "creality-water-washable",
        vendor: "Creality",
        name: "Water-Washable",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "creality-abs-like-resin",
        vendor: "Creality",
        name: "ABS-Like Resin",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "creality-high-precision-8k-resin",
        vendor: "Creality",
        name: "High-Precision 8K Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-k-k-tough-resin",
        vendor: "Resione",
        name: "K / K+ Tough Resin",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-m58-m68-light-grey-rigid-resin",
        vendor: "Resione",
        name: "M58 / M68 Light Grey Rigid Resin",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-th72-flexible-tough-resin",
        vendor: "Resione",
        name: "TH72 Flexible Tough Resin",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-f69-flexible-elastic-rubber-resin",
        vendor: "Resione",
        name: "F69 Flexible Elastic Rubber Resin",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-g217-clear-tough-resin",
        vendor: "Resione",
        name: "G217 Clear Tough Resin",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-w90b-water-washable",
        vendor: "Resione",
        name: "W90B Water Washable",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "resione-d01-dental-model",
        vendor: "Resione",
        name: "D01 Dental Model",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-strong-x",
        vendor: "Liqcreate",
        name: "Strong-X",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-clear-impact",
        vendor: "Liqcreate",
        name: "Clear Impact",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-composite-x",
        vendor: "Liqcreate",
        name: "Composite-X",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-flexible-x",
        vendor: "Liqcreate",
        name: "Flexible-X",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-elastomer-x",
        vendor: "Liqcreate",
        name: "Elastomer-X",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-hazard-glow",
        vendor: "Liqcreate",
        name: "Hazard Glow",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-wax-castable",
        vendor: "Liqcreate",
        name: "Wax Castable",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-premium-tough",
        vendor: "Liqcreate",
        name: "Premium Tough",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "liqcreate-bio-med-clear",
        vendor: "Liqcreate",
        name: "Bio-Med Clear",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-rapid-resin",
        vendor: "Monocure 3D",
        name: "Rapid Resin",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-pro-hard",
        vendor: "Monocure 3D",
        name: "Pro Hard",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-pro-tough",
        vendor: "Monocure 3D",
        name: "Pro Tough",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-pro-tensile",
        vendor: "Monocure 3D",
        name: "Pro Tensile",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-castable",
        vendor: "Monocure 3D",
        name: "Castable",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "monocure-3d-dental-model",
        vendor: "Monocure 3D",
        name: "Dental Model",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "ameralabs-tgm-7",
        vendor: "AmeraLabs",
        name: "TGM-7",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "ameralabs-amd-3",
        vendor: "AmeraLabs",
        name: "AMD-3",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "ameralabs-xvn-50",
        vendor: "AmeraLabs",
        name: "XVN-50",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "ameralabs-dmd-21",
        vendor: "AmeraLabs",
        name: "DMD-21",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "ameralabs-cranial-dental",
        vendor: "AmeraLabs",
        name: "Cranial Dental",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nexa3d-xabs3843",
        vendor: "Nexa3D",
        name: "xABS3843",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nexa3d-xce-black",
        vendor: "Nexa3D",
        name: "xCE-Black",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nexa3d-x45-natural",
        vendor: "Nexa3D",
        name: "x45-Natural",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nexa3d-xpp405",
        vendor: "Nexa3D",
        name: "xPP405",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nexa3d-xflex402",
        vendor: "Nexa3D",
        name: "xFLEX402",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-st-45",
        vendor: "BASF",
        name: "Ultracur3D ST 45",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-rg-35",
        vendor: "BASF",
        name: "Ultracur3D RG 35",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-el-60",
        vendor: "BASF",
        name: "Ultracur3D EL 60",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-fl-60",
        vendor: "BASF",
        name: "Ultracur3D FL 60",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-rg-1100",
        vendor: "BASF",
        name: "Ultracur3D RG 1100",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "basf-ultracur3d-st-80",
        vendor: "BASF",
        name: "Ultracur3D ST 80",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-3843-high-toughness",
        vendor: "Henkel",
        name: "Loctite 3D 3843 High Toughness",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-ind405",
        vendor: "Henkel",
        name: "Loctite 3D IND405",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-ind408",
        vendor: "Henkel",
        name: "Loctite 3D IND408",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-med412-biocompatible",
        vendor: "Henkel",
        name: "Loctite 3D MED412 Biocompatible",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-med413",
        vendor: "Henkel",
        name: "Loctite 3D MED413",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "henkel-loctite-3d-pro410",
        vendor: "Henkel",
        name: "Loctite 3D PRO410",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sartomer-n3xtdimension-resins",
        vendor: "Sartomer",
        name: "N3xtDimension Resins",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "evonik-infinam-st-6100-l",
        vendor: "Evonik",
        name: "INFINAM ST 6100 L",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "evonik-infinam-fl-6300-l",
        vendor: "Evonik",
        name: "INFINAM FL 6300 L",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keymodel-ultra",
        vendor: "KeyPrint",
        name: "KeyModel Ultra",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keyguide",
        vendor: "KeyPrint",
        name: "KeyGuide",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keysplint-soft",
        vendor: "KeyPrint",
        name: "KeySplint Soft",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keysplint-hard",
        vendor: "KeyPrint",
        name: "KeySplint Hard",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keycast",
        vendor: "KeyPrint",
        name: "KeyCast",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "keyprint-keyortho-ibt",
        vendor: "KeyPrint",
        name: "KeyOrtho IBT",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-die-and-model-2",
        vendor: "SprintRay",
        name: "Die and Model 2",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-splint-flex",
        vendor: "SprintRay",
        name: "Splint Flex",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-apex-teeth",
        vendor: "SprintRay",
        name: "Apex Teeth",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-apex-base",
        vendor: "SprintRay",
        name: "Apex Base",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-nightguard-flex",
        vendor: "SprintRay",
        name: "NightGuard Flex",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "sprintray-nightguard-firm",
        vendor: "SprintRay",
        name: "NightGuard Firm",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-5100-c-b-mfh",
        vendor: "NextDent",
        name: "5100 C&B MFH",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-sg-surgical-guide",
        vendor: "NextDent",
        name: "SG Surgical Guide",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-denture-3d",
        vendor: "NextDent",
        name: "Denture 3D+",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-cast",
        vendor: "NextDent",
        name: "Cast",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-ortho-rigid",
        vendor: "NextDent",
        name: "Ortho Rigid",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "nextdent-tray",
        vendor: "NextDent",
        name: "Tray",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "b9creations-emerald-castable",
        vendor: "B9Creations",
        name: "Emerald Castable",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "b9creations-yellow-castable",
        vendor: "B9Creations",
        name: "Yellow Castable",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "b9creations-rugged-nylon-like",
        vendor: "B9Creations",
        name: "Rugged Nylon-Like",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "b9creations-elastomer",
        vendor: "B9Creations",
        name: "Elastomer",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-standard-rigid-photopolymer",
        vendor: "Generic",
        name: "Standard Rigid Photopolymer",
        family: "Standard",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-fast-curing-draft",
        vendor: "Generic",
        name: "Fast-Curing Draft",
        family: "Draft",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-water-washable",
        vendor: "Generic",
        name: "Water-Washable",
        family: "Water-washable",
        wash: "water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-plant-based-eco",
        vendor: "Generic",
        name: "Plant-Based / Eco",
        family: "Plant-based",
        wash: "IPA or water",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-abs-like-impact-resistant",
        vendor: "Generic",
        name: "ABS-Like Impact-Resistant",
        family: "ABS-like",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-tough-polypropylene-like",
        vendor: "Generic",
        name: "Tough Polypropylene-Like",
        family: "Tough",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-high-elongation-flexible",
        vendor: "Generic",
        name: "High-Elongation Flexible",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-elastic-silicone-like",
        vendor: "Generic",
        name: "Elastic Silicone-Like",
        family: "Flexible",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-high-temperature",
        vendor: "Generic",
        name: "High-Temperature",
        family: "High-temperature",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-ceramic-filled-composite",
        vendor: "Generic",
        name: "Ceramic-Filled Composite",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-carbon-fiber-reinforced",
        vendor: "Generic",
        name: "Carbon Fiber-Reinforced",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-glass-filled",
        vendor: "Generic",
        name: "Glass-Filled",
        family: "Filled",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-castable-jewelry-wax",
        vendor: "Generic",
        name: "Castable Jewelry Wax",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-direct-burnout-dental-investment",
        vendor: "Generic",
        name: "Direct-Burnout Dental Investment",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-optically-clear",
        vendor: "Generic",
        name: "Optically Clear",
        family: "Clear",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-flame-retardant-ul94-v-0",
        vendor: "Generic",
        name: "Flame-Retardant UL94 V-0",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-esd-dissipative",
        vendor: "Generic",
        name: "ESD Dissipative",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-biocompatible-class-i",
        vendor: "Generic",
        name: "Biocompatible Class I",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-biocompatible-class-iia-surgical-guide",
        vendor: "Generic",
        name: "Biocompatible Class IIa Surgical Guide",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-temporary-crown-and-bridge",
        vendor: "Generic",
        name: "Temporary Crown and Bridge",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-permanent-ceramic-crown",
        vendor: "Generic",
        name: "Permanent Ceramic Crown",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-denture-base",
        vendor: "Generic",
        name: "Denture Base",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-denture-tooth",
        vendor: "Generic",
        name: "Denture Tooth",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-orthodontic-aligner",
        vendor: "Generic",
        name: "Orthodontic Aligner",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-gingiva-soft-tissue",
        vendor: "Generic",
        name: "Gingiva Soft-Tissue",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-castable-orthopedic",
        vendor: "Generic",
        name: "Castable Orthopedic",
        family: "Castable",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-radio-opaque-medical",
        vendor: "Generic",
        name: "Radio-Opaque Medical",
        family: "Dental",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-high-viscosity-engineering-pu",
        vendor: "Generic",
        name: "High-Viscosity Engineering PU",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-dual-cure-hybrid",
        vendor: "Generic",
        name: "Dual-Cure Hybrid",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-magnetic-particle",
        vendor: "Generic",
        name: "Magnetic-Particle",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-conductive-trace",
        vendor: "Generic",
        name: "Conductive Trace",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
    Resin {
        id: "generic-microfluidic-high-resolution",
        vendor: "Generic",
        name: "Microfluidic High-Resolution",
        family: "Specialty",
        wash: "IPA",
        density_g_ml: 1.10,
    },
];

pub const PROFILES: &[ResinProfile] = &[
    ResinProfile {
        resin_id: "anycubic-colored-uv",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 50.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-plant-based",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 50.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-dlp-craftsman",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 2.0,
        bottom_exposure_s: 35.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 8.0,
        lift_speed: 3.0,
        retract_speed: 4.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-uv-tough",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 50.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-water-wash",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 50.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-abs-like",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 35.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 2.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-abs-like-pro",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 3.0,
        bottom_exposure_s: 35.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
    ResinProfile {
        resin_id: "anycubic-high-clear",
        machine_id: "anycubic-photon-m3-max",
        layer_mm: 0.05,
        exposure_s: 4.5,
        bottom_exposure_s: 30.0,
        bottom_layers: 6,
        light_off_s: 2.5,
        lift_mm: 10.0,
        lift_speed: 2.0,
        retract_speed: 3.0,
        source: "Anycubic Photon M3 Max store guide, November 2023",
    },
];

pub fn find(id: &str) -> Option<&'static Resin> {
    RESINS.iter().find(|r| r.id == id)
}

pub fn find_name(name: &str) -> Option<&'static Resin> {
    RESINS.iter().find(|r| r.name == name)
}

/// Published profile for this resin on this printer, nearest layer height.
pub fn profile_for(
    resin_id: &str,
    machine_id: &str,
    layer_mm: f32,
) -> Option<&'static ResinProfile> {
    PROFILES
        .iter()
        .filter(|p| p.resin_id == resin_id && p.machine_id == machine_id)
        .min_by(|a, b| {
            let da = (a.layer_mm - layer_mm).abs();
            let db = (b.layer_mm - layer_mm).abs();
            da.total_cmp(&db)
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn m3_max_colored_uv_is_the_published_table() {
        let p = profile_for("anycubic-colored-uv", "anycubic-photon-m3-max", 0.05).unwrap();
        assert!((p.exposure_s - 3.0).abs() < 0.01);
        assert!((p.bottom_exposure_s - 50.0).abs() < 0.01);
        assert!(profile_for("elegoo-standard-resin", "anycubic-photon-m3-max", 0.05).is_none());
        assert!(RESINS.len() > 80);
        assert!(RESINS.iter().any(|r| r.family == "Dental"));
    }
}
